name: Deploy site estático no GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', se essa for sua branch principal

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Fazer upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # raiz do projeto, onde está seu index.html

      - name: Fazer deploy
        id: deployment
        uses: actions/deploy-pages@v4
